# Generated by Django 4.2.5 on 2023-09-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtfPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ticker", models.CharField(max_length=10)),
                ("price", models.FloatField()),
            ],
            options={
                "db_table": "etf_prices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Etf",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("avg_return", models.FloatField()),
                ("volatility", models.FloatField()),
                ("max_drop", models.FloatField()),
                ("sharpe_ratio", models.FloatField()),
                ("risk_cluster", models.IntegerField()),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BasicUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "inv_term",
                    models.CharField(
                        choices=[
                            ("short", "Less than 2 years"),
                            ("mid", "Between 2 and 5 years"),
                            ("long", "More than 5 years"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "inv_objective",
                    models.CharField(
                        choices=[
                            ("safeguard", "My priority is to maintain my capital"),
                            ("growth", "My priority is to grow my capital"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "loss_absortion",
                    models.CharField(
                        choices=[
                            (
                                "low",
                                "This are my life-long savings, I can't afford to loose",
                            ),
                            ("mid", "I can take some risk, but it has to be moderate"),
                            (
                                "high",
                                "I am willing to take higher risks if they lead to higher growth",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("risk_rating", models.IntegerField()),
                ("last_update_date", models.DateTimeField(auto_now=True)),
                (
                    "recommended_etfs",
                    models.ManyToManyField(related_name="etfs", to="etfs.etf"),
                ),
            ],
            options={
                "verbose_name": "BasicUser",
                "verbose_name_plural": "BasicUsers",
            },
        ),
    ]
