# Generated by Django 4.2.5 on 2023-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("inv_term", models.CharField(max_length=50)),
                ("inv_objective", models.CharField(max_length=50)),
                ("loss_absortion", models.CharField(max_length=50)),
                ("risk_rating", models.IntegerField()),
                ("last_update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BasicUser",
                "verbose_name_plural": "BasicUsers",
            },
        ),
    ]
